# Generated by Django 4.0.5 on 2022-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_todobase2_remove_todobase_ank1_remove_todobase_ank2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoBase2',
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todobase',
            name='ank6',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
