# Generated by Django 2.1.15 on 2023-01-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_todobase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todobase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
